// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7L2Zs5aOIAGKkdtCX0NCgxwMZ1P4v1eE',
    appId: '1:474658639331:web:eac3d15bfb16f370fbe4d6',
    messagingSenderId: '474658639331',
    projectId: 'guessthebox-b5778',
    authDomain: 'guessthebox-b5778.firebaseapp.com',
    storageBucket: 'guessthebox-b5778.appspot.com',
    measurementId: 'G-SPCC5XTCQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1uekM1vAAl2DRFt_ro_a9KPDW0GEpWo',
    appId: '1:474658639331:android:3dad383e6df86194fbe4d6',
    messagingSenderId: '474658639331',
    projectId: 'guessthebox-b5778',
    storageBucket: 'guessthebox-b5778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmKhskHypO5MEYTdstvhNe2dA8JKPLbhk',
    appId: '1:474658639331:ios:5ffaac1063c86427fbe4d6',
    messagingSenderId: '474658639331',
    projectId: 'guessthebox-b5778',
    storageBucket: 'guessthebox-b5778.appspot.com',
    iosBundleId: 'com.example.guessTheBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmKhskHypO5MEYTdstvhNe2dA8JKPLbhk',
    appId: '1:474658639331:ios:1169f09236d85477fbe4d6',
    messagingSenderId: '474658639331',
    projectId: 'guessthebox-b5778',
    storageBucket: 'guessthebox-b5778.appspot.com',
    iosBundleId: 'com.example.guessTheBox.RunnerTests',
  );
}
